// <auto-generated />
using System;
using LionDev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240309152701_cv1")]
    partial class cv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LionDev.Models.Producto", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeLosMasBuscados")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParaSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            IdProducto = new Guid("da43d14c-0557-42b6-89b3-1831e195701f"),
                            Cantidad = 15,
                            Color = "Negro",
                            Descripcion = "Chaqueta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Chaqueta",
                            ParaSexo = "Masculino",
                            Referencia = "C3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/C3.png",
                            Valor = 140000
                        },
                        new
                        {
                            IdProducto = new Guid("e1b26ab7-c2c1-4900-95cb-113f17eb6b6e"),
                            Cantidad = 15,
                            Color = "Blanco y rojo",
                            Descripcion = "Falda larga",
                            EsDeLosMasBuscados = true,
                            Nombre = "Falda larga",
                            ParaSexo = "Femenino",
                            Referencia = "FL3",
                            Talla = "14",
                            UrlImagen = "ProductosImagenes/FL3.png",
                            Valor = 35000
                        },
                        new
                        {
                            IdProducto = new Guid("80c481f4-2c24-4289-bfe7-0dae0928eb83"),
                            Cantidad = 25,
                            Color = "Blanco",
                            Descripcion = "Camiseta corta",
                            EsDeLosMasBuscados = true,
                            Nombre = "Camiseta",
                            ParaSexo = "Femenino",
                            Referencia = "CA5",
                            Talla = "16",
                            UrlImagen = "ProductosImagenes/CA5.png",
                            Valor = 45000
                        });
                });

            modelBuilder.Entity("LionDev.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("50c9c421-fc48-44f3-9b9a-0935651aecbe"),
                            Apellidos = "Falcao",
                            Contrasena = "Rada1",
                            CorreoElectronico = "rada@gmail.com",
                            Nombres = "Radamel",
                            Rol = "Comprador"
                        },
                        new
                        {
                            IdUsuario = new Guid("4bb03cec-6850-409b-b888-1ad38b838f40"),
                            Apellidos = "Olivera",
                            Contrasena = "Admin1",
                            CorreoElectronico = "carlos@gmail.com",
                            Nombres = "Carlos",
                            Rol = "Administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
